services:
  backend_app:
    build: .
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db