services:
  backend_app:
    build: .
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - 8000:8000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017